language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: make && make check
notifications:
    irc:
        channels:
          - "irc.freenode.org#kf-engine"
        template:
          - "[%{commit} : %{author}] %{message} "
        skip_join: true
